SHOW DATABASES ;
USE bambooKey;
SHOW TABLES;
SHOW FULL TABLES;
SHOW TABLES FROM bambooKey;
SELECT * FROM user;
SELECT * FROM product;
SELECT * FROM PRODUCT_REVIEW;
SELECT * FROM CART;
SELECT * FROM ORDERED;
SELECT * FROM QUESTIONS;

